# Generated by Django 4.2.dev20220909115147 on 2022-09-17 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data2019', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='data',
            old_name='FOP_ID',
            new_name='FOD_ID',
        ),
    ]
