# Generated by Django 4.2.dev20220909115147 on 2022-09-17 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data2019', '0002_rename_fop_id_data_fod_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='NWCG_REPORTING_UNIT_ID',
            field=models.CharField(max_length=8, null=True),
        ),
    ]
